[package]
name = "oas3"
version = "0.0.1"
edition = "2018"
authors = ["robjtede <robjtede@icloud.com>", "softprops <d.tangren@gmail.com>"]
description = "Structures and tools to parse and navigate OpenAPI v3 specifications."
# repository = "https://github.com/softprops/openapi"
keywords = ["oas", "oas3", "openapi", "openapi3", "swagger"]
license = "MIT"

[dependencies]
http = "0.1"
bytes = "0.4"
derive_more = "0.15"
err-derive = "0.1"
lazy_static = "1"
log = "0.4"
regex = "1"
semver = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
url = "1.7"
url_serde = "0.2"
reqwest = "0.9"

[dev-dependencies]
dotenv = "0.14"
colored = "1"
envy = "0.4"
maplit = "1"
pretty_assertions = "0.6"
pretty_env_logger = "0.3"
prettytable-rs = "0.8"

[features]
default = ["conformance"]
validation = []
conformance = ["validation"]
