[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
repository = "https://github.com/x52dev/oas3-rs"
license = "MIT"
edition = "2021"
rust-version = "1.75"

[workspace.lints.rust]
rust_2018_idioms = "deny"
nonstandard_style = "deny"
future_incompatible = "deny"
missing_debug_implementations = { level = "warn", priority = -1 }
