[package]
name = "oas3"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>", "softprops <d.tangren@gmail.com>"]
description = "Structures and tools to parse, navigate and validate OpenAPI v3 specifications."
keywords = ["oas3", "openapi", "swagger", "api", "validation"]
license = "MIT"
edition = "2018"

[features]
default = ["validation", "conformance"]
validation = []
conformance = ["validation"]

[dependencies]
bytes = "0.5"
colored = "2"
derive_more = "0.99"
http = "0.2"
lazy_static = "1"
log = "0.4"
maplit = "1"
prettytable-rs = "0.8"
regex = "1"
reqwest = { version = "0.10", features = ["json"] }
semver = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
color-eyre = "0.5"
dotenv = "0.15"
eyre = "0.6"
pretty_assertions = "0.6"
pretty_env_logger = "0.4"
tokio = { version = "0.2", features = ["full"] }

[[example]]
name = "conformance"
required-features = ["conformance"]
